components_manager:
#    coro_pool:
#	    initial_size: 50
#	    max_size: 100

    task_processors:
        grpc-blocking-task-processor:  # For blocking gRPC channel creation
            worker_threads: 2
            thread_name: grpc-worker
        main-task-processor:           # For non-blocking operations
            worker_threads: 8
            thread_name: main-worker
        fs-task-processor:             # For blocking filesystem operations
            worker_threads: 2
            thread_name: fs-worker
    default_task_processor: main-task-processor  # Task processor in which components start.

    components:
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: error
                    overflow_behavior: discard

        server:
            listener:
                port: 8092
                task_processor: main-task-processor

        grpc-server:
            port: 8091 
            completion-queue-count: 3

        counter-service:
            task-processor: main-task-processor
            service-prefix: Counter
            middlewares: [ ]

        redis-database:
            groups:
                - config_name: main_db  # Key to lookup in secdist configuration
                  db: main_db           # Name to refer to the cluster in components::Redis::GetClient()

            subscribe_groups:  # Array of redis clusters to work with in subscribe mode
            thread_pools:
                redis_thread_pool_size: 8
                sentinel_thread_pool_size: 1

        secdist:                                         # Component that stores configuration of hosts and passwords
            provider: default-secdist-provider
        default-secdist-provider:                        # Component that loads configuration of hosts and passwords
            config: /home/boris/UServer/cls_userver/configs/secdist.json  # Values are supposed to be stored in this file
            missing-ok: true                             # ... but if the file is missing it is still ok
            environment-secrets-key: SECDIST_CONFIG      # ... values will be loaded from this environment value

        testsuite-support:



